Update wiiu.md
PretendoNetwork/website pull request #223
Opened 2023-10-04 18:58 UTC by ExperiencersInternational

Fixed incorrect spelling of navigate, and fixed PNID not being capitalised on the last line, as well as adding a full stop to that sentence.

2023-10-04 19:00 UTC, ExperiencersInternational commented
I did a pretty bad job at noticing some of the other minor mistakes oops

2023-10-04 19:19 UTC, jonbarrow requested changes

2023-10-04 19:19 UTC, jonbarrow commented on docs/en_US/install/wiiu.md
> +Finally, set up your PNID, email and password. Once all of this is done, you will be able to use Pretendo Servers.
```suggestion
Finally, set up your PNID, email and password. Once all of this is done, you will be able to use Pretendo servers.
```

2023-10-04 19:19 UTC, jonbarrow commented on docs/en_US/install/wiiu.md
> +Right before registering a PNID, please make sure to save your password on some sort of note, as you will not be able to reset your password. After registering just simply change your birth date, gen
While we're here, password resetting has been implemented for a long time. So the section about it not being implemented is no longer needed

2023-10-04 19:48 UTC, ExperiencersInternational commented
Should be resolved now, let me know if there are still issues. Might edit the 3DS guide as well considering it doesn't tell you how to sign in on a 3DS (just did this), and it might be useful just telling people how to go to Luma settings if need be

I need to get my Wii U modded already in all honesty

2023-10-05 05:08 UTC, gitlimes commented
Looks good to me! @jonbarrow hbu?

2023-10-05 07:31 UTC, jonbarrow commented
@gitlimes i trust your judgment, you can merge if it looks good

2023-10-06 04:32 UTC, gitlimes commented
Well, merging then. Thank you for your contribution!

2023-10-06 04:32 UTC, merged