Added screenshots to local file directory
PretendoNetwork/website pull request #265
Opened 2024-04-08 20:27 UTC by Auxy6858

Fixed images not appearing

2024-04-11 16:57 UTC, Auxy6858 commented
@jonbarrow I added the images locally

2024-04-11 16:57 UTC, Auxy6858 commented
This is a new PR, I closed the other one

2024-04-24 13:24 UTC, jonbarrow requested changes
Please test your changes locally before making PRs, the current changes would not work when deployed

2024-04-24 13:24 UTC, jonbarrow commented on blogposts/9-29-21.md
> +![](../public/assets/images/blogposts/9-29-21/Notifications3DS.png)
None of these links will work. The `public` folder is not exposed to the client, only the files/folders *within* the `public` folder

Also we do not use relative links here. You can see the other blog posts for how to do this

2024-04-24 13:27 UTC, jonbarrow commented
Also your changes are on the wrong branch. Do not PR into the master branch, we have a dev branch for changes

2024-08-21 01:42 UTC, closed without merging