Add Spanish translation
PretendoNetwork/website pull request #33
Opened 2021-05-03 14:09 UTC by Angel3245

2021-08-22 13:40 UTC, mrjvs requested changes

2021-08-22 13:40 UTC, mrjvs commented on locales/ES_es.json
> +			},
jon has a new username on github, please change to this:
```suggestion
			{
				"name": "Jonathan Barrow (jonbarrow)",
				"caption": "Líder del proyecto y desarrollador principal",
				"picture": "https://github.com/jonbarrow.png",
				"github": "https://github.com/jonbarrow"
			},
```

2021-08-22 17:20 UTC, mrjvs approved these changes

2021-08-22 17:20 UTC, mrjvs commented
great, thanks a lot

2021-08-22 17:20 UTC, merged

2022-08-06 18:38 UTC, ashmonty commented
Hey @Angel3245, I'm Ash from the Pretendo Network developer team.

I'm contacting you because you have contributed to our `PretendoNetwork/website` repository in the past, and we're working on relicensing it under the AGPL3 license (https://choosealicense.com/licenses/agpl-3.0/), which protects the code from being used in closed-source projects, while still permitting modification, as long as the source code is made available. To do so, we need to ask every contributor to also relicense their contributions to AGPL3.

Do you agree to relicense your contribution(s) under AGPL3? (Yes/No)

P.S: I'm asking you here because I wasn't sure where to reach you otherwise

2022-08-17 08:44 UTC, Angel3245 commented
> Hey @Angel3245, I'm Ash from the Pretendo Network developer team.
> 
> I'm contacting you because you have contributed to our `PretendoNetwork/website` repository in the past, and we're working on relicensing it under the AGPL3 license (https://choosealicense.com/licenses/agpl-3.0/), which protects the code from being used in closed-source projects, while still permitting modification, as long as the source code is made available. To do so, we need to ask every contributor to also relicense their contributions to AGPL3.
> 
> Do you agree to relicense your contribution(s) under AGPL3? (Yes/No)
> 
> P.S: I'm asking you here because I wasn't sure where to reach you otherwise

Yes