Brazilian Portuguese translation to Pretendo Network
PretendoNetwork/website pull request #39
Opened 2021-05-26 17:49 UTC by Jao154

2021-05-26 17:55 UTC, JipFr requested changes

2021-05-26 17:55 UTC, JipFr commented on locales/PT_br.json
> +		"subtitle": "Game servers",
Is this right?￼

2021-05-26 17:55 UTC, JipFr commented on locales/PT_br.json
> +				"resposta": "Pretendo is an open source Nintendo Network replacement that aims to build custom servers for the Wii U and 3DS family of consoles. Our goal is to preserve the online functionality o
Looks like you missed a translation here￼

2021-05-26 17:55 UTC, JipFr commented on locales/PT_br.json
> +				"resposta": "Sim, você precisará desbloquear seu dispositivo para se conectar; no entanto, no Wii U você só precisará acessar o Homebrew Launcher (ou seja, Haxchi, Coldboot Haxchi ou mesmo o expl
There is some invalid JSON here￼

2021-08-22 13:35 UTC, mrjvs requested changes
can be merged after the json file is in proper syntax (check the review comments)

2021-08-22 13:35 UTC, mrjvs commented on locales/PT_br.json
> +			},
There is an end quote missing on line 61

2021-08-22 13:37 UTC, mrjvs commented on locales/PT_br.json
> +				"github": "https://github.com/RedDuckss"
change to this. he has a new username
```suggestion
				"name": "Jonathan Barrow (jonbarrow)",
				"caption": "Criador do projeto e desenvolvedor chefe",
				"picture": "https://github.com/jonbarrow.png",
				"github": "https://github.com/jonbarrow"
```

2021-09-11 21:21 UTC, montylion commented
Closed in favor of #57. You're welcome to provide feedback to the accepted localization.

2021-09-11 21:21 UTC, closed without merging